# Generated by Django 4.1 on 2022-10-15 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_messageto_email_messageto_is_read_messageto_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messageto',
            old_name='service',
            new_name='mess_service',
        ),
    ]
