# Generated by Django 4.1 on 2022-10-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_messageto_mess_receiver_messageto_mess_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageto',
            name='reply',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
