# Generated by Django 4.1 on 2022-10-22 13:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_messageto_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageto',
            name='reply',
        ),
        migrations.AddField(
            model_name='messageto',
            name='reply_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
