# Generated by Django 4.1 on 2022-09-08 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='Address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='GST_Number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='Shop_Name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='role',
            field=models.CharField(blank=True, choices=[('Supplier', 'Supplier'), ('Consumer', 'Consumer')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profiles',
            name='service_image',
            field=models.ImageField(blank=True, null=True, upload_to='service-images/'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='email',
            field=models.EmailField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
