# Generated by Django 4.1 on 2022-09-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profiles_address_profiles_gst_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
