# Generated by Django 4.1 on 2022-09-10 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profiles_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='service_image',
            new_name='featured_image',
        ),
    ]
