# Generated by Django 4.1 on 2022-09-11 06:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_rename_service_image_profiles_featured_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profiles',
            new_name='profile',
        ),
    ]
