# Generated by Django 4.1 on 2022-08-31 09:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Category',
            fields=[
                ('category_name', models.CharField(max_length=200)),
                ('category_description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('service_name', models.CharField(max_length=200)),
                ('service_description', models.TextField()),
                ('featured_image', models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('category', models.ManyToManyField(blank=True, to='services.service_category')),
            ],
        ),
    ]
