# Generated by Django 4.1 on 2022-08-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Event_Services',
        ),
        migrations.AlterField(
            model_name='service_category',
            name='category_description',
            field=models.TextField(blank=True),
        ),
    ]
