# Generated by Django 4.1 on 2022-08-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_rename_services_event_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_services',
            name='category',
            field=models.ManyToManyField(to='services.service_category'),
        ),
    ]
