# Generated by Django 4.1 on 2022-08-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_event_services_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_services',
            name='category',
            field=models.ManyToManyField(blank=True, to='services.service_category'),
        ),
    ]
