# Generated by Django 4.1 on 2022-09-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_event_services_vote_ratio_event_services_vote_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_services',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
