# Generated by Django 4.1 on 2022-09-12 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_event_services_service_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event_services',
            name='service_owner',
        ),
    ]
