# Generated by Django 4.1 on 2022-09-12 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_profiles_profile'),
        ('services', '0009_remove_event_services_service_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_services',
            name='service_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
