# Generated by Django 4.1 on 2022-10-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_booking_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
