# Generated by Django 4.1 on 2022-11-02 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_rename_date_booking_end_date_booking_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='start_time',
        ),
    ]
